project:
  type: website

execute: 
  freeze: auto

bibliography: references.bib

website:
  # title: "CFC Wiki"
  repo-url: https://github.com/utcfc/utcfc.github.io
  repo-actions: [edit]
  navbar:
    logo: images/CFC-LOGO-2color-bigtext.png
    search: true
    right:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Pages"
        href: pages.qmd
      - icon: github
        href: https://github.com/utcfc/utcfc.github.io/
        target: _blank

  sidebar: 
    - title: "About"
      collapse-level: 1
      contents:
        - text: "About"
          href: about.qmd
        - text: "Team"
          href: authors.qmd
        - text: "Contributing"
          href: contributing.qmd
        
    - title: "Pages"
      collapse-level: 1
      contents:
        - text: "All Pages"
          href: pages.qmd
        - text: "Recently Updated"
          href: recents.qmd
        - section: Data Compilations
          contents: pages/data/*
    
  back-to-top-navigation: true
  # margin-header: |
    # ![](images/CFC-LOGO-2color.png)
  # body-footer: |
  #   Last updated {{<meta date-modified>}} by {{<meta author>}}.
  #   ![](images/CFC-LOGO-2color.png){.external width="200px"}
  #   [![GitHub](https://img.shields.io/github/stars/hollisakins/cfc?style=social)](

format:
  html:
    theme: assets/theme-light.scss
    css: assets/styles.css
    code-block-border-left: true
    highlight-style: assets/light.theme
    sidebar: true
    toc: true
    toc-location: right
    from: markdown+emoji
    reference-location: document
    citation-location: document
    #smooth-scroll: true
    link-external-newwindow: true

