on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Install a stable Python and make it available to Quarto
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Use a widely-supported version with many prebuilt wheels
          python-version: '3.11'

      # Install Jupyter (required by Quarto's Jupyter engine) and your Python deps
      - name: Install Python dependencies for Quarto
        run: |
          python -m pip install --upgrade pip
          # Jupyter stack needed by Quarto when executing Python chunks
          pip install jupyter nbformat ipykernel
          # Common libs used in your .qmd (adjust as needed)
          pip install numpy pandas matplotlib astropy tabulate

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Tell Quarto which Python to use (the one we just set up)
          QUARTO_PYTHON: python
